language: php

sudo: false

cache:
  directories:
    - ~/.composer/cache/files

php:
  - 7.4

env:
  - SYMFONY_VERSION=4.4.*
  - SYMFONY_VERSION=5.0.*
  - PHPUNIT_VERSION=^7.0
  - PHPUNIT_VERSION=^8.0
  - PHPUNIT_VERSION=^9.0
  - MOST_RECENT=true

jobs:
  exclude:
    - php: 7.2
      env:
        - PHPUNIT_VERSION=^9.0

before_install:
  - phpenv config-rm xdebug.ini || true

install:
  - |
    if [ ! -z "${SYMFONY_VERSION}" ]
    then
        composer require "symfony/browser-kit:${SYMFONY_VERSION}" --no-update --no-scripts --prefer-dist
        composer require "symfony/finder:${SYMFONY_VERSION}" --no-update --no-scripts --prefer-dist
        composer require "symfony/framework-bundle:${SYMFONY_VERSION}" --no-update --no-scripts --prefer-dist
        composer require --dev "symfony/serializer:${SYMFONY_VERSION}" --no-update --no-scripts --prefer-dist
    fi

  - |
    if [ ! -z "${PHPUNIT_VERSION}" ]
    then
        composer require --dev "phpunit/phpunit:${PHPUNIT_VERSION}" --no-update --no-scripts --prefer-dist
    fi

  - COMPOSER_MEMORY_LIMIT=-1 composer update --prefer-dist

before_script:
  - test/app/console doctrine:schema:update --force -vvv

script:
  - composer validate --strict
  - composer analyse

  - vendor/bin/phpunit
